// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client.sql

package db

import (
	"context"
	"time"
)

const consumeClientToken = `-- name: ConsumeClientToken :one
UPDATE client_token SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING id, end_user_id, kind, token_hash, ticket_id, expires_at, used_at, created_at
`

func (q *Queries) ConsumeClientToken(ctx context.Context, tokenHash string) (ClientToken, error) {
	row := q.db.QueryRow(ctx, consumeClientToken, tokenHash)
	var i ClientToken
	err := row.Scan(
		&i.ID,
		&i.EndUserID,
		&i.Kind,
		&i.TokenHash,
		&i.TicketID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countPortalTickets = `-- name: CountPortalTickets :one
SELECT count(*) FROM ticket t JOIN ticket_status s ON s.id = t.status_id
WHERE t.user_id = $1
  AND ($2::text IS NULL OR s.state::text = $2)
`

type CountPortalTicketsParams struct {
	UserID *int64
	State  *string
}

func (q *Queries) CountPortalTickets(ctx context.Context, arg CountPortalTicketsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPortalTickets, arg.UserID, arg.State)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClientRefreshToken = `-- name: CreateClientRefreshToken :exec
INSERT INTO client_refresh_token (token_hash, end_user_id, ticket_id, expires_at) VALUES ($1, $2, $3, $4)
`

type CreateClientRefreshTokenParams struct {
	TokenHash string
	EndUserID int64
	TicketID  *int64
	ExpiresAt time.Time
}

func (q *Queries) CreateClientRefreshToken(ctx context.Context, arg CreateClientRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createClientRefreshToken,
		arg.TokenHash,
		arg.EndUserID,
		arg.TicketID,
		arg.ExpiresAt,
	)
	return err
}

const createClientToken = `-- name: CreateClientToken :exec
INSERT INTO client_token (end_user_id, kind, token_hash, ticket_id, expires_at) VALUES ($1, $2, $3, $4, $5)
`

type CreateClientTokenParams struct {
	EndUserID int64
	Kind      ClientTokenKind
	TokenHash string
	TicketID  *int64
	ExpiresAt time.Time
}

func (q *Queries) CreateClientToken(ctx context.Context, arg CreateClientTokenParams) error {
	_, err := q.db.Exec(ctx, createClientToken,
		arg.EndUserID,
		arg.Kind,
		arg.TokenHash,
		arg.TicketID,
		arg.ExpiresAt,
	)
	return err
}

const createEndUser = `-- name: CreateEndUser :one
INSERT INTO end_user (email, name) VALUES ($1, $2) RETURNING id, email, name, password_hash, email_verified_at, created_at, updated_at
`

type CreateEndUserParams struct {
	Email string
	Name  string
}

func (q *Queries) CreateEndUser(ctx context.Context, arg CreateEndUserParams) (EndUser, error) {
	row := q.db.QueryRow(ctx, createEndUser, arg.Email, arg.Name)
	var i EndUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const firstStatusInState = `-- name: FirstStatusInState :one
SELECT id, name, state FROM ticket_status WHERE state = $1 ORDER BY sort_order, id LIMIT 1
`

type FirstStatusInStateRow struct {
	ID    int64
	Name  string
	State TicketState
}

func (q *Queries) FirstStatusInState(ctx context.Context, state TicketState) (FirstStatusInStateRow, error) {
	row := q.db.QueryRow(ctx, firstStatusInState, state)
	var i FirstStatusInStateRow
	err := row.Scan(&i.ID, &i.Name, &i.State)
	return i, err
}

const getClientRefreshToken = `-- name: GetClientRefreshToken :one
SELECT id, token_hash, end_user_id, ticket_id, expires_at, revoked_at, created_at, updated_at FROM client_refresh_token WHERE token_hash = $1
`

func (q *Queries) GetClientRefreshToken(ctx context.Context, tokenHash string) (ClientRefreshToken, error) {
	row := q.db.QueryRow(ctx, getClientRefreshToken, tokenHash)
	var i ClientRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.EndUserID,
		&i.TicketID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndUser = `-- name: GetEndUser :one
SELECT id, email, name, password_hash, email_verified_at, created_at, updated_at FROM end_user WHERE id = $1
`

func (q *Queries) GetEndUser(ctx context.Context, id int64) (EndUser, error) {
	row := q.db.QueryRow(ctx, getEndUser, id)
	var i EndUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndUserByEmail = `-- name: GetEndUserByEmail :one
SELECT id, email, name, password_hash, email_verified_at, created_at, updated_at FROM end_user WHERE lower(email) = lower($1)
`

func (q *Queries) GetEndUserByEmail(ctx context.Context, lower string) (EndUser, error) {
	row := q.db.QueryRow(ctx, getEndUserByEmail, lower)
	var i EndUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPortalTicket = `-- name: GetPortalTicket :one
SELECT t.id, t.number, t.subject, t.user_id, t.status_id, s.name AS status_name, s.state, d.name AS dept_name,
       h.name AS topic_name, t.created_at, t.updated_at, t.last_message_at, t.closed_at
FROM ticket t JOIN ticket_status s ON s.id = t.status_id JOIN department d ON d.id = t.dept_id
LEFT JOIN help_topic h ON h.id = t.topic_id
WHERE t.id = $1
`

type GetPortalTicketRow struct {
	ID            int64
	Number        string
	Subject       string
	UserID        *int64
	StatusID      int64
	StatusName    string
	State         TicketState
	DeptName      string
	TopicName     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LastMessageAt time.Time
	ClosedAt      *time.Time
}

func (q *Queries) GetPortalTicket(ctx context.Context, id int64) (GetPortalTicketRow, error) {
	row := q.db.QueryRow(ctx, getPortalTicket, id)
	var i GetPortalTicketRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Subject,
		&i.UserID,
		&i.StatusID,
		&i.StatusName,
		&i.State,
		&i.DeptName,
		&i.TopicName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastMessageAt,
		&i.ClosedAt,
	)
	return i, err
}

const getTicketIDByNumberAndEmail = `-- name: GetTicketIDByNumberAndEmail :one
SELECT id FROM ticket WHERE number = $1 AND lower(requester_email) = lower($2)
`

type GetTicketIDByNumberAndEmailParams struct {
	Number string
	Lower  string
}

func (q *Queries) GetTicketIDByNumberAndEmail(ctx context.Context, arg GetTicketIDByNumberAndEmailParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTicketIDByNumberAndEmail, arg.Number, arg.Lower)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listActiveTopics = `-- name: ListActiveTopics :many
SELECT id, name FROM help_topic WHERE is_active ORDER BY sort_order, name
`

type ListActiveTopicsRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListActiveTopics(ctx context.Context) ([]ListActiveTopicsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTopicsRow{}
	for rows.Next() {
		var i ListActiveTopicsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortalThread = `-- name: ListPortalThread :many
SELECT e.id, e.type, e.body, e.format, e.created_at, e.user_id, e.staff_id, e.poster,
       u.name AS user_name, st.first_name, st.last_name, st.username
FROM thread_entry e
LEFT JOIN end_user u ON u.id = e.user_id
LEFT JOIN staff st ON st.id = e.staff_id
WHERE e.ticket_id = $1 AND e.type IN ('message', 'response')
ORDER BY e.id
`

type ListPortalThreadRow struct {
	ID        int64
	Type      ThreadEntryType
	Body      string
	Format    BodyFormat
	CreatedAt time.Time
	UserID    *int64
	StaffID   *int64
	Poster    string
	UserName  *string
	FirstName *string
	LastName  *string
	Username  *string
}

func (q *Queries) ListPortalThread(ctx context.Context, ticketID int64) ([]ListPortalThreadRow, error) {
	rows, err := q.db.Query(ctx, listPortalThread, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPortalThreadRow{}
	for rows.Next() {
		var i ListPortalThreadRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Body,
			&i.Format,
			&i.CreatedAt,
			&i.UserID,
			&i.StaffID,
			&i.Poster,
			&i.UserName,
			&i.FirstName,
			&i.LastName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPortalTickets = `-- name: ListPortalTickets :many
SELECT t.id, t.number, t.subject, t.status_id, s.name AS status_name, s.state, d.name AS dept_name,
       t.created_at, t.last_message_at, t.closed_at
FROM ticket t JOIN ticket_status s ON s.id = t.status_id JOIN department d ON d.id = t.dept_id
WHERE t.user_id = $1
  AND ($2::text IS NULL OR s.state::text = $2)
ORDER BY t.last_message_at DESC, t.id DESC
LIMIT $4 OFFSET $3
`

type ListPortalTicketsParams struct {
	UserID *int64
	State  *string
	Off    int32
	Lim    int32
}

type ListPortalTicketsRow struct {
	ID            int64
	Number        string
	Subject       string
	StatusID      int64
	StatusName    string
	State         TicketState
	DeptName      string
	CreatedAt     time.Time
	LastMessageAt time.Time
	ClosedAt      *time.Time
}

func (q *Queries) ListPortalTickets(ctx context.Context, arg ListPortalTicketsParams) ([]ListPortalTicketsRow, error) {
	rows, err := q.db.Query(ctx, listPortalTickets,
		arg.UserID,
		arg.State,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPortalTicketsRow{}
	for rows.Next() {
		var i ListPortalTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Subject,
			&i.StatusID,
			&i.StatusName,
			&i.State,
			&i.DeptName,
			&i.CreatedAt,
			&i.LastMessageAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicDepartments = `-- name: ListPublicDepartments :many
SELECT id, name FROM department WHERE is_public ORDER BY name
`

type ListPublicDepartmentsRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListPublicDepartments(ctx context.Context) ([]ListPublicDepartmentsRow, error) {
	rows, err := q.db.Query(ctx, listPublicDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicDepartmentsRow{}
	for rows.Next() {
		var i ListPublicDepartmentsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEndUserVerified = `-- name: MarkEndUserVerified :exec
UPDATE end_user SET email_verified_at = COALESCE(email_verified_at, now()), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkEndUserVerified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markEndUserVerified, id)
	return err
}

const revokeClientRefreshToken = `-- name: RevokeClientRefreshToken :exec
UPDATE client_refresh_token SET revoked_at = now(), updated_at = now() WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeClientRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeClientRefreshToken, tokenHash)
	return err
}

const revokeClientRefreshTokensForUser = `-- name: RevokeClientRefreshTokensForUser :exec
UPDATE client_refresh_token SET revoked_at = now(), updated_at = now() WHERE end_user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeClientRefreshTokensForUser(ctx context.Context, endUserID int64) error {
	_, err := q.db.Exec(ctx, revokeClientRefreshTokensForUser, endUserID)
	return err
}

const setEndUserPassword = `-- name: SetEndUserPassword :exec
UPDATE end_user SET password_hash = $2, email_verified_at = COALESCE(email_verified_at, now()), updated_at = now() WHERE id = $1
`

type SetEndUserPasswordParams struct {
	ID           int64
	PasswordHash *string
}

func (q *Queries) SetEndUserPassword(ctx context.Context, arg SetEndUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setEndUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const setThreadEntryUser = `-- name: SetThreadEntryUser :exec
UPDATE thread_entry SET user_id = $2 WHERE id = $1
`

type SetThreadEntryUserParams struct {
	ID     int64
	UserID *int64
}

func (q *Queries) SetThreadEntryUser(ctx context.Context, arg SetThreadEntryUserParams) error {
	_, err := q.db.Exec(ctx, setThreadEntryUser, arg.ID, arg.UserID)
	return err
}

const setTicketUser = `-- name: SetTicketUser :exec
UPDATE ticket SET user_id = $2 WHERE id = $1
`

type SetTicketUserParams struct {
	ID     int64
	UserID *int64
}

func (q *Queries) SetTicketUser(ctx context.Context, arg SetTicketUserParams) error {
	_, err := q.db.Exec(ctx, setTicketUser, arg.ID, arg.UserID)
	return err
}

const updateEndUserName = `-- name: UpdateEndUserName :one
UPDATE end_user SET name = $2, updated_at = now() WHERE id = $1 RETURNING id, email, name, password_hash, email_verified_at, created_at, updated_at
`

type UpdateEndUserNameParams struct {
	ID   int64
	Name string
}

func (q *Queries) UpdateEndUserName(ctx context.Context, arg UpdateEndUserNameParams) (EndUser, error) {
	row := q.db.QueryRow(ctx, updateEndUserName, arg.ID, arg.Name)
	var i EndUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
