// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const dashboardByDepartment = `-- name: DashboardByDepartment :many
SELECT d.id, d.name,
       count(*) FILTER (WHERE e.kind = 'created')  AS opened,
       count(*) FILTER (WHERE e.kind = 'assigned') AS assigned,
       count(*) FILTER (WHERE e.kind = 'closed')   AS closed,
       count(*) FILTER (WHERE e.kind = 'reopened') AS reopened
FROM ticket_event e
JOIN ticket t ON t.id = e.ticket_id
JOIN department d ON d.id = t.dept_id
WHERE e.created_at >= $1 AND e.created_at < $2
  AND e.kind IN ('created', 'assigned', 'closed', 'reopened')
  AND ($3::boolean OR t.dept_id = ANY($4::bigint[]))
GROUP BY d.id, d.name ORDER BY d.name
`

type DashboardByDepartmentParams struct {
	FromAt   time.Time
	ToAt     time.Time
	AllDepts bool
	DeptIds  []int64
}

type DashboardByDepartmentRow struct {
	ID       int64
	Name     string
	Opened   int64
	Assigned int64
	Closed   int64
	Reopened int64
}

func (q *Queries) DashboardByDepartment(ctx context.Context, arg DashboardByDepartmentParams) ([]DashboardByDepartmentRow, error) {
	rows, err := q.db.Query(ctx, dashboardByDepartment,
		arg.FromAt,
		arg.ToAt,
		arg.AllDepts,
		arg.DeptIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardByDepartmentRow{}
	for rows.Next() {
		var i DashboardByDepartmentRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Opened,
			&i.Assigned,
			&i.Closed,
			&i.Reopened,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardByStaff = `-- name: DashboardByStaff :many
SELECT s.id, s.first_name, s.last_name, s.username,
       count(*) FILTER (WHERE e.kind = 'created')  AS opened,
       count(*) FILTER (WHERE e.kind = 'assigned') AS assigned,
       count(*) FILTER (WHERE e.kind = 'closed')   AS closed,
       count(*) FILTER (WHERE e.kind = 'reopened') AS reopened
FROM ticket_event e
JOIN ticket t ON t.id = e.ticket_id
LEFT JOIN staff s ON s.id = e.staff_id
WHERE e.created_at >= $1 AND e.created_at < $2
  AND e.kind IN ('created', 'assigned', 'closed', 'reopened')
  AND ($3::boolean OR t.dept_id = ANY($4::bigint[]))
GROUP BY s.id, s.first_name, s.last_name, s.username ORDER BY s.username NULLS LAST
`

type DashboardByStaffParams struct {
	FromAt   time.Time
	ToAt     time.Time
	AllDepts bool
	DeptIds  []int64
}

type DashboardByStaffRow struct {
	ID        *int64
	FirstName *string
	LastName  *string
	Username  *string
	Opened    int64
	Assigned  int64
	Closed    int64
	Reopened  int64
}

func (q *Queries) DashboardByStaff(ctx context.Context, arg DashboardByStaffParams) ([]DashboardByStaffRow, error) {
	rows, err := q.db.Query(ctx, dashboardByStaff,
		arg.FromAt,
		arg.ToAt,
		arg.AllDepts,
		arg.DeptIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardByStaffRow{}
	for rows.Next() {
		var i DashboardByStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.Opened,
			&i.Assigned,
			&i.Closed,
			&i.Reopened,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardByTopic = `-- name: DashboardByTopic :many
SELECT h.id, h.name,
       count(*) FILTER (WHERE e.kind = 'created')  AS opened,
       count(*) FILTER (WHERE e.kind = 'assigned') AS assigned,
       count(*) FILTER (WHERE e.kind = 'closed')   AS closed,
       count(*) FILTER (WHERE e.kind = 'reopened') AS reopened
FROM ticket_event e
JOIN ticket t ON t.id = e.ticket_id
LEFT JOIN help_topic h ON h.id = t.topic_id
WHERE e.created_at >= $1 AND e.created_at < $2
  AND e.kind IN ('created', 'assigned', 'closed', 'reopened')
  AND ($3::boolean OR t.dept_id = ANY($4::bigint[]))
GROUP BY h.id, h.name ORDER BY h.name NULLS LAST
`

type DashboardByTopicParams struct {
	FromAt   time.Time
	ToAt     time.Time
	AllDepts bool
	DeptIds  []int64
}

type DashboardByTopicRow struct {
	ID       *int64
	Name     *string
	Opened   int64
	Assigned int64
	Closed   int64
	Reopened int64
}

func (q *Queries) DashboardByTopic(ctx context.Context, arg DashboardByTopicParams) ([]DashboardByTopicRow, error) {
	rows, err := q.db.Query(ctx, dashboardByTopic,
		arg.FromAt,
		arg.ToAt,
		arg.AllDepts,
		arg.DeptIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardByTopicRow{}
	for rows.Next() {
		var i DashboardByTopicRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Opened,
			&i.Assigned,
			&i.Closed,
			&i.Reopened,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardSeries = `-- name: DashboardSeries :many
SELECT (date_trunc('day', e.created_at AT TIME ZONE 'UTC'))::date AS day,
       count(*) FILTER (WHERE e.kind = 'created')  AS opened,
       count(*) FILTER (WHERE e.kind = 'assigned') AS assigned,
       count(*) FILTER (WHERE e.kind = 'closed')   AS closed,
       count(*) FILTER (WHERE e.kind = 'reopened') AS reopened
FROM ticket_event e
JOIN ticket t ON t.id = e.ticket_id
WHERE e.created_at >= $1 AND e.created_at < $2
  AND e.kind IN ('created', 'assigned', 'closed', 'reopened')
  AND ($3::boolean OR t.dept_id = ANY($4::bigint[]))
GROUP BY 1 ORDER BY 1
`

type DashboardSeriesParams struct {
	FromAt   time.Time
	ToAt     time.Time
	AllDepts bool
	DeptIds  []int64
}

type DashboardSeriesRow struct {
	Day      pgtype.Date
	Opened   int64
	Assigned int64
	Closed   int64
	Reopened int64
}

func (q *Queries) DashboardSeries(ctx context.Context, arg DashboardSeriesParams) ([]DashboardSeriesRow, error) {
	rows, err := q.db.Query(ctx, dashboardSeries,
		arg.FromAt,
		arg.ToAt,
		arg.AllDepts,
		arg.DeptIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DashboardSeriesRow{}
	for rows.Next() {
		var i DashboardSeriesRow
		if err := rows.Scan(
			&i.Day,
			&i.Opened,
			&i.Assigned,
			&i.Closed,
			&i.Reopened,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
