// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dept.sql

package db

import (
	"context"
)

const firstDepartment = `-- name: FirstDepartment :one
SELECT id, name, is_public, manager_id, created_at, updated_at FROM department ORDER BY id LIMIT 1
`

func (q *Queries) FirstDepartment(ctx context.Context) (Department, error) {
	row := q.db.QueryRow(ctx, firstDepartment)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPublic,
		&i.ManagerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepartment = `-- name: GetDepartment :one
SELECT id, name, is_public, manager_id, created_at, updated_at FROM department WHERE id = $1
`

func (q *Queries) GetDepartment(ctx context.Context, id int64) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartment, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPublic,
		&i.ManagerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
