// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file.sql

package db

import (
	"context"
)

const createAttachment = `-- name: CreateAttachment :exec
INSERT INTO attachment (thread_entry_id, file_id, inline) VALUES ($1, $2, false)
`

type CreateAttachmentParams struct {
	ThreadEntryID int64
	FileID        int64
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.Exec(ctx, createAttachment, arg.ThreadEntryID, arg.FileID)
	return err
}

const createFile = `-- name: CreateFile :one
INSERT INTO file (key, name, mime, size, sha256, backend, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, key, name, mime, size, sha256, backend, uploaded_by, created_at, updated_at
`

type CreateFileParams struct {
	Key        string
	Name       string
	Mime       string
	Size       int64
	Sha256     string
	Backend    string
	UploadedBy *int64
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.Key,
		arg.Name,
		arg.Mime,
		arg.Size,
		arg.Sha256,
		arg.Backend,
		arg.UploadedBy,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Mime,
		&i.Size,
		&i.Sha256,
		&i.Backend,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT id, key, name, mime, size, sha256, backend, uploaded_by, created_at, updated_at FROM file WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Mime,
		&i.Size,
		&i.Sha256,
		&i.Backend,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isFileAttached = `-- name: IsFileAttached :one
SELECT EXISTS (SELECT 1 FROM attachment WHERE file_id = $1)::boolean
`

func (q *Queries) IsFileAttached(ctx context.Context, fileID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isFileAttached, fileID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
