// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file.sql

package db

import (
	"context"
	"time"
)

const createAttachment = `-- name: CreateAttachment :exec
INSERT INTO attachment (thread_entry_id, file_id, inline) VALUES ($1, $2, false)
`

type CreateAttachmentParams struct {
	ThreadEntryID int64
	FileID        int64
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.Exec(ctx, createAttachment, arg.ThreadEntryID, arg.FileID)
	return err
}

const createFile = `-- name: CreateFile :one
INSERT INTO file (key, name, mime, size, sha256, backend, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, key, name, mime, size, sha256, backend, uploaded_by, created_at, updated_at
`

type CreateFileParams struct {
	Key        string
	Name       string
	Mime       string
	Size       int64
	Sha256     string
	Backend    string
	UploadedBy *int64
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.Key,
		arg.Name,
		arg.Mime,
		arg.Size,
		arg.Sha256,
		arg.Backend,
		arg.UploadedBy,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Mime,
		&i.Size,
		&i.Sha256,
		&i.Backend,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUnattachedFile = `-- name: DeleteUnattachedFile :execrows
DELETE FROM file f
WHERE f.id = $1
  AND NOT EXISTS (SELECT 1 FROM attachment a WHERE a.file_id = f.id)
`

func (q *Queries) DeleteUnattachedFile(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnattachedFile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const fileOnCustomerEntry = `-- name: FileOnCustomerEntry :one
SELECT EXISTS (
  SELECT 1 FROM attachment a
  JOIN thread_entry te ON te.id = a.thread_entry_id
  WHERE a.file_id = $1 AND te.ticket_id = $2 AND te.type IN ('message', 'response')
)::boolean
`

type FileOnCustomerEntryParams struct {
	FileID   int64
	TicketID int64
}

// Whether the file is attached to a customer-visible entry (a message or a
// response, never a note) of the ticket.
func (q *Queries) FileOnCustomerEntry(ctx context.Context, arg FileOnCustomerEntryParams) (bool, error) {
	row := q.db.QueryRow(ctx, fileOnCustomerEntry, arg.FileID, arg.TicketID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const fileTicketDeptID = `-- name: FileTicketDeptID :one
SELECT t.dept_id
FROM attachment a
JOIN thread_entry te ON te.id = a.thread_entry_id
JOIN ticket t ON t.id = te.ticket_id
WHERE a.file_id = $1
LIMIT 1
`

func (q *Queries) FileTicketDeptID(ctx context.Context, fileID int64) (int64, error) {
	row := q.db.QueryRow(ctx, fileTicketDeptID, fileID)
	var dept_id int64
	err := row.Scan(&dept_id)
	return dept_id, err
}

const getFile = `-- name: GetFile :one
SELECT id, key, name, mime, size, sha256, backend, uploaded_by, created_at, updated_at FROM file WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Mime,
		&i.Size,
		&i.Sha256,
		&i.Backend,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isFileAttached = `-- name: IsFileAttached :one
SELECT EXISTS (SELECT 1 FROM attachment WHERE file_id = $1)::boolean
`

func (q *Queries) IsFileAttached(ctx context.Context, fileID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isFileAttached, fileID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listUnattachedFilesBefore = `-- name: ListUnattachedFilesBefore :many
SELECT f.id, f.key, f.name, f.mime, f.size, f.sha256, f.backend, f.uploaded_by, f.created_at, f.updated_at FROM file f
WHERE f.created_at < $1
  AND NOT EXISTS (SELECT 1 FROM attachment a WHERE a.file_id = f.id)
ORDER BY f.id
`

func (q *Queries) ListUnattachedFilesBefore(ctx context.Context, createdAt time.Time) ([]File, error) {
	rows, err := q.db.Query(ctx, listUnattachedFilesBefore, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Mime,
			&i.Size,
			&i.Sha256,
			&i.Backend,
			&i.UploadedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
