// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mail.sql

package db

import (
	"context"
	"time"
)

const claimOutbox = `-- name: ClaimOutbox :many
UPDATE email_outbox SET attempts = attempts + 1, updated_at = now()
WHERE id IN (
  SELECT id FROM email_outbox
  WHERE status = 'pending' AND next_attempt_at <= now()
  ORDER BY next_attempt_at
  LIMIT $1
  FOR UPDATE SKIP LOCKED
)
RETURNING id, ticket_id, entry_id, template_key, to_address, to_name, subject, body_html, body_text, message_id, in_reply_to, auto_submitted, status, attempts, last_error, next_attempt_at, sent_at, created_at, updated_at
`

func (q *Queries) ClaimOutbox(ctx context.Context, limit int32) ([]EmailOutbox, error) {
	rows, err := q.db.Query(ctx, claimOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailOutbox{}
	for rows.Next() {
		var i EmailOutbox
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.EntryID,
			&i.TemplateKey,
			&i.ToAddress,
			&i.ToName,
			&i.Subject,
			&i.BodyHtml,
			&i.BodyText,
			&i.MessageID,
			&i.InReplyTo,
			&i.AutoSubmitted,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countInbound = `-- name: CountInbound :one
SELECT count(*) FROM inbound_message
`

func (q *Queries) CountInbound(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countInbound)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOutbox = `-- name: CountOutbox :one
SELECT count(*) FROM email_outbox
WHERE ($1::email_status IS NULL OR status = $1::email_status)
`

func (q *Queries) CountOutbox(ctx context.Context, status *EmailStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countOutbox, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInbound = `-- name: CreateInbound :one
INSERT INTO inbound_message (message_id, from_address, from_name, subject, ticket_id, entry_id, outcome, reason)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, message_id, from_address, from_name, subject, ticket_id, entry_id, outcome, reason, received_at
`

type CreateInboundParams struct {
	MessageID   string
	FromAddress string
	FromName    string
	Subject     string
	TicketID    *int64
	EntryID     *int64
	Outcome     InboundOutcome
	Reason      string
}

func (q *Queries) CreateInbound(ctx context.Context, arg CreateInboundParams) (InboundMessage, error) {
	row := q.db.QueryRow(ctx, createInbound,
		arg.MessageID,
		arg.FromAddress,
		arg.FromName,
		arg.Subject,
		arg.TicketID,
		arg.EntryID,
		arg.Outcome,
		arg.Reason,
	)
	var i InboundMessage
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FromAddress,
		&i.FromName,
		&i.Subject,
		&i.TicketID,
		&i.EntryID,
		&i.Outcome,
		&i.Reason,
		&i.ReceivedAt,
	)
	return i, err
}

const createOutbox = `-- name: CreateOutbox :one
INSERT INTO email_outbox (ticket_id, entry_id, template_key, to_address, to_name, subject, body_html, body_text, message_id, in_reply_to, auto_submitted)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type CreateOutboxParams struct {
	TicketID      *int64
	EntryID       *int64
	TemplateKey   string
	ToAddress     string
	ToName        string
	Subject       string
	BodyHtml      string
	BodyText      string
	MessageID     string
	InReplyTo     *string
	AutoSubmitted bool
}

func (q *Queries) CreateOutbox(ctx context.Context, arg CreateOutboxParams) (int64, error) {
	row := q.db.QueryRow(ctx, createOutbox,
		arg.TicketID,
		arg.EntryID,
		arg.TemplateKey,
		arg.ToAddress,
		arg.ToName,
		arg.Subject,
		arg.BodyHtml,
		arg.BodyText,
		arg.MessageID,
		arg.InReplyTo,
		arg.AutoSubmitted,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getEmailTemplate = `-- name: GetEmailTemplate :one
SELECT id, key, subject, body_html, body_text, created_at, updated_at FROM email_template WHERE key = $1
`

func (q *Queries) GetEmailTemplate(ctx context.Context, key string) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, getEmailTemplate, key)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInboundByMessageID = `-- name: GetInboundByMessageID :one
SELECT id, message_id, from_address, from_name, subject, ticket_id, entry_id, outcome, reason, received_at FROM inbound_message WHERE message_id = $1
`

func (q *Queries) GetInboundByMessageID(ctx context.Context, messageID string) (InboundMessage, error) {
	row := q.db.QueryRow(ctx, getInboundByMessageID, messageID)
	var i InboundMessage
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.FromAddress,
		&i.FromName,
		&i.Subject,
		&i.TicketID,
		&i.EntryID,
		&i.Outcome,
		&i.Reason,
		&i.ReceivedAt,
	)
	return i, err
}

const getOutbox = `-- name: GetOutbox :one
SELECT id, ticket_id, entry_id, template_key, to_address, to_name, subject, body_html, body_text, message_id, in_reply_to, auto_submitted, status, attempts, last_error, next_attempt_at, sent_at, created_at, updated_at FROM email_outbox WHERE id = $1
`

func (q *Queries) GetOutbox(ctx context.Context, id int64) (EmailOutbox, error) {
	row := q.db.QueryRow(ctx, getOutbox, id)
	var i EmailOutbox
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.EntryID,
		&i.TemplateKey,
		&i.ToAddress,
		&i.ToName,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.MessageID,
		&i.InReplyTo,
		&i.AutoSubmitted,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.NextAttemptAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lastSentMessageID = `-- name: LastSentMessageID :one
SELECT message_id FROM email_outbox
WHERE ticket_id = $1 AND to_address = $2 AND status = 'sent'
ORDER BY sent_at DESC LIMIT 1
`

type LastSentMessageIDParams struct {
	TicketID  *int64
	ToAddress string
}

func (q *Queries) LastSentMessageID(ctx context.Context, arg LastSentMessageIDParams) (string, error) {
	row := q.db.QueryRow(ctx, lastSentMessageID, arg.TicketID, arg.ToAddress)
	var message_id string
	err := row.Scan(&message_id)
	return message_id, err
}

const listEmailTemplates = `-- name: ListEmailTemplates :many
SELECT id, key, subject, body_html, body_text, created_at, updated_at FROM email_template ORDER BY key
`

func (q *Queries) ListEmailTemplates(ctx context.Context) ([]EmailTemplate, error) {
	rows, err := q.db.Query(ctx, listEmailTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailTemplate{}
	for rows.Next() {
		var i EmailTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Subject,
			&i.BodyHtml,
			&i.BodyText,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInbound = `-- name: ListInbound :many
SELECT id, message_id, from_address, from_name, subject, ticket_id, entry_id, outcome, reason, received_at FROM inbound_message ORDER BY id DESC LIMIT $1 OFFSET $2
`

type ListInboundParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListInbound(ctx context.Context, arg ListInboundParams) ([]InboundMessage, error) {
	rows, err := q.db.Query(ctx, listInbound, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboundMessage{}
	for rows.Next() {
		var i InboundMessage
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.FromAddress,
			&i.FromName,
			&i.Subject,
			&i.TicketID,
			&i.EntryID,
			&i.Outcome,
			&i.Reason,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutbox = `-- name: ListOutbox :many
SELECT id, ticket_id, entry_id, template_key, to_address, to_name, subject, status, attempts, last_error, next_attempt_at, sent_at, created_at
FROM email_outbox
WHERE ($1::email_status IS NULL OR status = $1::email_status)
ORDER BY id DESC
LIMIT $3 OFFSET $2
`

type ListOutboxParams struct {
	Status *EmailStatus
	Off    int32
	Lim    int32
}

type ListOutboxRow struct {
	ID            int64
	TicketID      *int64
	EntryID       *int64
	TemplateKey   string
	ToAddress     string
	ToName        string
	Subject       string
	Status        EmailStatus
	Attempts      int32
	LastError     *string
	NextAttemptAt time.Time
	SentAt        *time.Time
	CreatedAt     time.Time
}

func (q *Queries) ListOutbox(ctx context.Context, arg ListOutboxParams) ([]ListOutboxRow, error) {
	rows, err := q.db.Query(ctx, listOutbox, arg.Status, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutboxRow{}
	for rows.Next() {
		var i ListOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.EntryID,
			&i.TemplateKey,
			&i.ToAddress,
			&i.ToName,
			&i.Subject,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE email_outbox SET last_error = $2, next_attempt_at = $3, status = $4, updated_at = now() WHERE id = $1
`

type MarkOutboxFailedParams struct {
	ID            int64
	LastError     *string
	NextAttemptAt time.Time
	Status        EmailStatus
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed,
		arg.ID,
		arg.LastError,
		arg.NextAttemptAt,
		arg.Status,
	)
	return err
}

const markOutboxSent = `-- name: MarkOutboxSent :exec
UPDATE email_outbox SET status = 'sent', sent_at = now(), last_error = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) MarkOutboxSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxSent, id)
	return err
}

const retryOutbox = `-- name: RetryOutbox :execrows
UPDATE email_outbox SET status = 'pending', attempts = 0, next_attempt_at = now(), last_error = NULL, updated_at = now()
WHERE id = $1 AND status <> 'sent'
`

func (q *Queries) RetryOutbox(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, retryOutbox, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEmailTemplate = `-- name: UpdateEmailTemplate :one
UPDATE email_template SET
  subject = COALESCE($1, subject),
  body_html = COALESCE($2, body_html),
  body_text = COALESCE($3, body_text),
  updated_at = now()
WHERE key = $4
RETURNING id, key, subject, body_html, body_text, created_at, updated_at
`

type UpdateEmailTemplateParams struct {
	Subject  *string
	BodyHtml *string
	BodyText *string
	Key      string
}

func (q *Queries) UpdateEmailTemplate(ctx context.Context, arg UpdateEmailTemplateParams) (EmailTemplate, error) {
	row := q.db.QueryRow(ctx, updateEmailTemplate,
		arg.Subject,
		arg.BodyHtml,
		arg.BodyText,
		arg.Key,
	)
	var i EmailTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Subject,
		&i.BodyHtml,
		&i.BodyText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
