// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"
)

type BodyFormat string

const (
	BodyFormatHtml BodyFormat = "html"
	BodyFormatText BodyFormat = "text"
)

func (e *BodyFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BodyFormat(s)
	case string:
		*e = BodyFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for BodyFormat: %T", src)
	}
	return nil
}

type NullBodyFormat struct {
	BodyFormat BodyFormat
	Valid      bool // Valid is true if BodyFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBodyFormat) Scan(value interface{}) error {
	if value == nil {
		ns.BodyFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BodyFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBodyFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BodyFormat), nil
}

type ThreadEntryType string

const (
	ThreadEntryTypeMessage  ThreadEntryType = "message"
	ThreadEntryTypeResponse ThreadEntryType = "response"
	ThreadEntryTypeNote     ThreadEntryType = "note"
)

func (e *ThreadEntryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ThreadEntryType(s)
	case string:
		*e = ThreadEntryType(s)
	default:
		return fmt.Errorf("unsupported scan type for ThreadEntryType: %T", src)
	}
	return nil
}

type NullThreadEntryType struct {
	ThreadEntryType ThreadEntryType
	Valid           bool // Valid is true if ThreadEntryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullThreadEntryType) Scan(value interface{}) error {
	if value == nil {
		ns.ThreadEntryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ThreadEntryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullThreadEntryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ThreadEntryType), nil
}

type TicketEventKind string

const (
	TicketEventKindCreated       TicketEventKind = "created"
	TicketEventKindAssigned      TicketEventKind = "assigned"
	TicketEventKindUnassigned    TicketEventKind = "unassigned"
	TicketEventKindStatusChanged TicketEventKind = "status_changed"
	TicketEventKindTransferred   TicketEventKind = "transferred"
	TicketEventKindClosed        TicketEventKind = "closed"
	TicketEventKindReopened      TicketEventKind = "reopened"
	TicketEventKindEdited        TicketEventKind = "edited"
)

func (e *TicketEventKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketEventKind(s)
	case string:
		*e = TicketEventKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketEventKind: %T", src)
	}
	return nil
}

type NullTicketEventKind struct {
	TicketEventKind TicketEventKind
	Valid           bool // Valid is true if TicketEventKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketEventKind) Scan(value interface{}) error {
	if value == nil {
		ns.TicketEventKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketEventKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketEventKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketEventKind), nil
}

type TicketSource string

const (
	TicketSourceWeb   TicketSource = "web"
	TicketSourceApi   TicketSource = "api"
	TicketSourcePhone TicketSource = "phone"
	TicketSourceOther TicketSource = "other"
)

func (e *TicketSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketSource(s)
	case string:
		*e = TicketSource(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketSource: %T", src)
	}
	return nil
}

type NullTicketSource struct {
	TicketSource TicketSource
	Valid        bool // Valid is true if TicketSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketSource) Scan(value interface{}) error {
	if value == nil {
		ns.TicketSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketSource), nil
}

type TicketState string

const (
	TicketStateOpen     TicketState = "open"
	TicketStateResolved TicketState = "resolved"
	TicketStateClosed   TicketState = "closed"
)

func (e *TicketState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketState(s)
	case string:
		*e = TicketState(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketState: %T", src)
	}
	return nil
}

type NullTicketState struct {
	TicketState TicketState
	Valid       bool // Valid is true if TicketState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketState) Scan(value interface{}) error {
	if value == nil {
		ns.TicketState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketState), nil
}

type Attachment struct {
	ThreadEntryID int64
	FileID        int64
	Inline        bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Department struct {
	ID        int64
	Name      string
	IsPublic  bool
	ManagerID *int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type File struct {
	ID         int64
	Key        string
	Name       string
	Mime       string
	Size       int64
	Sha256     string
	Backend    string
	UploadedBy *int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type HelpTopic struct {
	ID         int64
	Name       string
	DeptID     *int64
	PriorityID *int64
	IsActive   bool
	SortOrder  int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type RefreshToken struct {
	ID        int64
	TokenHash string
	StaffID   int64
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Staff struct {
	ID            int64
	Username      string
	Email         string
	PasswordHash  string
	FirstName     string
	LastName      string
	IsAdmin       bool
	IsActive      bool
	PrimaryDeptID int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type StaffDepartment struct {
	StaffID   int64
	DeptID    int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ThreadEntry struct {
	ID        int64
	TicketID  int64
	Type      ThreadEntryType
	StaffID   *int64
	Poster    string
	Title     *string
	Body      string
	Format    BodyFormat
	ParentID  *int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Ticket struct {
	ID              int64
	Number          string
	Subject         string
	StatusID        int64
	DeptID          int64
	TopicID         *int64
	PriorityID      int64
	AssignedStaffID *int64
	RequesterName   string
	RequesterEmail  string
	Source          TicketSource
	IsAnswered      bool
	DueAt           *time.Time
	ClosedAt        *time.Time
	LastMessageAt   time.Time
	LastResponseAt  *time.Time
	Extra           []byte
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type TicketEvent struct {
	ID        int64
	TicketID  int64
	StaffID   *int64
	Kind      TicketEventKind
	Data      []byte
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TicketPriority struct {
	ID        int64
	Name      string
	Urgency   int32
	Color     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TicketStatus struct {
	ID        int64
	Name      string
	State     TicketState
	SortOrder int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
