// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ref.sql

package db

import (
	"context"
)

const defaultPriority = `-- name: DefaultPriority :one
SELECT id, name, urgency, color, created_at, updated_at FROM ticket_priority ORDER BY (name = 'normal') DESC, urgency LIMIT 1
`

func (q *Queries) DefaultPriority(ctx context.Context) (TicketPriority, error) {
	row := q.db.QueryRow(ctx, defaultPriority)
	var i TicketPriority
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Urgency,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const defaultStatus = `-- name: DefaultStatus :one
SELECT id, name, state, sort_order, created_at, updated_at FROM ticket_status WHERE state = 'open' ORDER BY sort_order LIMIT 1
`

func (q *Queries) DefaultStatus(ctx context.Context) (TicketStatus, error) {
	row := q.db.QueryRow(ctx, defaultStatus)
	var i TicketStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.State,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPriority = `-- name: GetPriority :one
SELECT id, name, urgency, color, created_at, updated_at FROM ticket_priority WHERE id = $1
`

func (q *Queries) GetPriority(ctx context.Context, id int64) (TicketPriority, error) {
	row := q.db.QueryRow(ctx, getPriority, id)
	var i TicketPriority
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Urgency,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStatus = `-- name: GetStatus :one
SELECT id, name, state, sort_order, created_at, updated_at FROM ticket_status WHERE id = $1
`

func (q *Queries) GetStatus(ctx context.Context, id int64) (TicketStatus, error) {
	row := q.db.QueryRow(ctx, getStatus, id)
	var i TicketStatus
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.State,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPriorities = `-- name: ListPriorities :many
SELECT id, name, urgency, color, created_at, updated_at FROM ticket_priority ORDER BY urgency
`

func (q *Queries) ListPriorities(ctx context.Context) ([]TicketPriority, error) {
	rows, err := q.db.Query(ctx, listPriorities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketPriority{}
	for rows.Next() {
		var i TicketPriority
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Urgency,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatuses = `-- name: ListStatuses :many
SELECT id, name, state, sort_order, created_at, updated_at FROM ticket_status ORDER BY sort_order
`

func (q *Queries) ListStatuses(ctx context.Context) ([]TicketStatus, error) {
	rows, err := q.db.Query(ctx, listStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TicketStatus{}
	for rows.Next() {
		var i TicketStatus
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.State,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
