// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_token.sql

package db

import (
	"context"
	"time"
)

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
UPDATE refresh_token SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
RETURNING id, token_hash, staff_id, expires_at, revoked_at, created_at, updated_at
`

func (q *Queries) ConsumeRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.StaffID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_token (token_hash, staff_id, expires_at) VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	TokenHash string
	StaffID   int64
	ExpiresAt time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.TokenHash, arg.StaffID, arg.ExpiresAt)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_token SET revoked_at = now()
WHERE token_hash = $1 AND staff_id = $2 AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	TokenHash string
	StaffID   int64
}

// Scoped to staff_id so a staff member can only ever revoke their own
// token: logout must never let one caller revoke someone else's session.
func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.TokenHash, arg.StaffID)
	return err
}

const revokeStaffRefreshTokens = `-- name: RevokeStaffRefreshTokens :exec
UPDATE refresh_token SET revoked_at = now() WHERE staff_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeStaffRefreshTokens(ctx context.Context, staffID int64) error {
	_, err := q.db.Exec(ctx, revokeStaffRefreshTokens, staffID)
	return err
}
