// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staff.sql

package db

import (
	"context"
)

const addStaffDepartment = `-- name: AddStaffDepartment :exec
INSERT INTO staff_department (staff_id, dept_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddStaffDepartmentParams struct {
	StaffID int64
	DeptID  int64
}

func (q *Queries) AddStaffDepartment(ctx context.Context, arg AddStaffDepartmentParams) error {
	_, err := q.db.Exec(ctx, addStaffDepartment, arg.StaffID, arg.DeptID)
	return err
}

const createStaff = `-- name: CreateStaff :one
INSERT INTO staff (username, email, password_hash, first_name, last_name, is_admin, is_active, primary_dept_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, username, email, password_hash, first_name, last_name, is_admin, is_active, primary_dept_id, created_at, updated_at
`

type CreateStaffParams struct {
	Username      string
	Email         string
	PasswordHash  string
	FirstName     string
	LastName      string
	IsAdmin       bool
	IsActive      bool
	PrimaryDeptID int64
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, createStaff,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.IsAdmin,
		arg.IsActive,
		arg.PrimaryDeptID,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.IsAdmin,
		&i.IsActive,
		&i.PrimaryDeptID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaff = `-- name: GetStaff :one
SELECT id, username, email, password_hash, first_name, last_name, is_admin, is_active, primary_dept_id, created_at, updated_at FROM staff WHERE id = $1
`

func (q *Queries) GetStaff(ctx context.Context, id int64) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaff, id)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.IsAdmin,
		&i.IsActive,
		&i.PrimaryDeptID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffByUsername = `-- name: GetStaffByUsername :one
SELECT id, username, email, password_hash, first_name, last_name, is_admin, is_active, primary_dept_id, created_at, updated_at FROM staff WHERE username = $1
`

func (q *Queries) GetStaffByUsername(ctx context.Context, username string) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByUsername, username)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.IsAdmin,
		&i.IsActive,
		&i.PrimaryDeptID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaffDepartmentIDs = `-- name: ListStaffDepartmentIDs :many
SELECT dept_id FROM staff_department WHERE staff_id = $1 ORDER BY dept_id
`

func (q *Queries) ListStaffDepartmentIDs(ctx context.Context, staffID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listStaffDepartmentIDs, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var dept_id int64
		if err := rows.Scan(&dept_id); err != nil {
			return nil, err
		}
		items = append(items, dept_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
