// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staff.sql

package db

import (
	"context"
)

const addStaffDepartment = `-- name: AddStaffDepartment :exec
INSERT INTO staff_department (staff_id, dept_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddStaffDepartmentParams struct {
	StaffID int64
	DeptID  int64
}

func (q *Queries) AddStaffDepartment(ctx context.Context, arg AddStaffDepartmentParams) error {
	_, err := q.db.Exec(ctx, addStaffDepartment, arg.StaffID, arg.DeptID)
	return err
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*)::bigint FROM staff WHERE is_admin AND is_active
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createStaff = `-- name: CreateStaff :one
INSERT INTO staff (username, email, password_hash, first_name, last_name, is_admin, is_active, primary_dept_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, username, email, password_hash, first_name, last_name, is_admin, is_active, primary_dept_id, created_at, updated_at
`

type CreateStaffParams struct {
	Username      string
	Email         string
	PasswordHash  string
	FirstName     string
	LastName      string
	IsAdmin       bool
	IsActive      bool
	PrimaryDeptID int64
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, createStaff,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.IsAdmin,
		arg.IsActive,
		arg.PrimaryDeptID,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.IsAdmin,
		&i.IsActive,
		&i.PrimaryDeptID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStaffDepartments = `-- name: DeleteStaffDepartments :exec
DELETE FROM staff_department WHERE staff_id = $1
`

func (q *Queries) DeleteStaffDepartments(ctx context.Context, staffID int64) error {
	_, err := q.db.Exec(ctx, deleteStaffDepartments, staffID)
	return err
}

const getStaff = `-- name: GetStaff :one
SELECT id, username, email, password_hash, first_name, last_name, is_admin, is_active, primary_dept_id, created_at, updated_at FROM staff WHERE id = $1
`

func (q *Queries) GetStaff(ctx context.Context, id int64) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaff, id)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.IsAdmin,
		&i.IsActive,
		&i.PrimaryDeptID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffByUsername = `-- name: GetStaffByUsername :one
SELECT id, username, email, password_hash, first_name, last_name, is_admin, is_active, primary_dept_id, created_at, updated_at FROM staff WHERE username = $1
`

func (q *Queries) GetStaffByUsername(ctx context.Context, username string) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByUsername, username)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.IsAdmin,
		&i.IsActive,
		&i.PrimaryDeptID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaff = `-- name: ListStaff :many
SELECT id, username, email, password_hash, first_name, last_name, is_admin, is_active, primary_dept_id, created_at, updated_at FROM staff ORDER BY username
`

func (q *Queries) ListStaff(ctx context.Context) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Staff{}
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.IsAdmin,
			&i.IsActive,
			&i.PrimaryDeptID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffDepartmentIDs = `-- name: ListStaffDepartmentIDs :many
SELECT dept_id FROM staff_department WHERE staff_id = $1 ORDER BY dept_id
`

func (q *Queries) ListStaffDepartmentIDs(ctx context.Context, staffID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listStaffDepartmentIDs, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var dept_id int64
		if err := rows.Scan(&dept_id); err != nil {
			return nil, err
		}
		items = append(items, dept_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStaffPassword = `-- name: SetStaffPassword :execrows
UPDATE staff SET password_hash = $2, updated_at = now() WHERE id = $1
`

type SetStaffPasswordParams struct {
	ID           int64
	PasswordHash string
}

func (q *Queries) SetStaffPassword(ctx context.Context, arg SetStaffPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStaffPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const staffCanSeeDept = `-- name: StaffCanSeeDept :one
SELECT EXISTS (
  SELECT 1 FROM staff s
  LEFT JOIN staff_department sd ON sd.staff_id = s.id AND sd.dept_id = $1
  WHERE s.id = $2 AND (s.is_admin OR s.primary_dept_id = $1 OR sd.dept_id IS NOT NULL)
)::boolean AS can_see
`

type StaffCanSeeDeptParams struct {
	DeptID  int64
	StaffID int64
}

func (q *Queries) StaffCanSeeDept(ctx context.Context, arg StaffCanSeeDeptParams) (bool, error) {
	row := q.db.QueryRow(ctx, staffCanSeeDept, arg.DeptID, arg.StaffID)
	var can_see bool
	err := row.Scan(&can_see)
	return can_see, err
}

const updateStaff = `-- name: UpdateStaff :one
UPDATE staff
SET email = COALESCE($1, email),
    first_name = COALESCE($2, first_name),
    last_name = COALESCE($3, last_name),
    is_admin = COALESCE($4, is_admin),
    is_active = COALESCE($5, is_active),
    primary_dept_id = COALESCE($6, primary_dept_id),
    updated_at = now()
WHERE id = $7
RETURNING id, username, email, password_hash, first_name, last_name, is_admin, is_active, primary_dept_id, created_at, updated_at
`

type UpdateStaffParams struct {
	Email         *string
	FirstName     *string
	LastName      *string
	IsAdmin       *bool
	IsActive      *bool
	PrimaryDeptID *int64
	ID            int64
}

func (q *Queries) UpdateStaff(ctx context.Context, arg UpdateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, updateStaff,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.IsAdmin,
		arg.IsActive,
		arg.PrimaryDeptID,
		arg.ID,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.IsAdmin,
		&i.IsActive,
		&i.PrimaryDeptID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
