// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: thread.sql

package db

import (
	"context"
	"time"
)

const listAttachmentsForEntries = `-- name: ListAttachmentsForEntries :many
SELECT a.thread_entry_id, a.file_id, a.inline, f.name, f.mime, f.size
FROM attachment a
JOIN file f ON f.id = a.file_id
WHERE a.thread_entry_id = ANY($1::bigint[])
ORDER BY a.thread_entry_id, a.file_id
`

type ListAttachmentsForEntriesRow struct {
	ThreadEntryID int64
	FileID        int64
	Inline        bool
	Name          string
	Mime          string
	Size          int64
}

func (q *Queries) ListAttachmentsForEntries(ctx context.Context, entryIds []int64) ([]ListAttachmentsForEntriesRow, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForEntries, entryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttachmentsForEntriesRow{}
	for rows.Next() {
		var i ListAttachmentsForEntriesRow
		if err := rows.Scan(
			&i.ThreadEntryID,
			&i.FileID,
			&i.Inline,
			&i.Name,
			&i.Mime,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadEntries = `-- name: ListThreadEntries :many
SELECT id, ticket_id, type, staff_id, poster, title, body, format, parent_id, created_at, updated_at FROM thread_entry
WHERE ticket_id = $1 AND id > $2
ORDER BY id
LIMIT $3::int
`

type ListThreadEntriesParams struct {
	TicketID  int64
	After     int64
	PageLimit int32
}

func (q *Queries) ListThreadEntries(ctx context.Context, arg ListThreadEntriesParams) ([]ThreadEntry, error) {
	rows, err := q.db.Query(ctx, listThreadEntries, arg.TicketID, arg.After, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThreadEntry{}
	for rows.Next() {
		var i ThreadEntry
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.Type,
			&i.StaffID,
			&i.Poster,
			&i.Title,
			&i.Body,
			&i.Format,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketEvents = `-- name: ListTicketEvents :many
SELECT e.id, e.ticket_id, e.staff_id, s.first_name AS staff_first_name, s.last_name AS staff_last_name,
       e.kind, e.data, e.created_at
FROM ticket_event e
LEFT JOIN staff s ON s.id = e.staff_id
WHERE e.ticket_id = $1
ORDER BY e.id
`

type ListTicketEventsRow struct {
	ID             int64
	TicketID       int64
	StaffID        *int64
	StaffFirstName *string
	StaffLastName  *string
	Kind           TicketEventKind
	Data           []byte
	CreatedAt      time.Time
}

func (q *Queries) ListTicketEvents(ctx context.Context, ticketID int64) ([]ListTicketEventsRow, error) {
	rows, err := q.db.Query(ctx, listTicketEvents, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketEventsRow{}
	for rows.Next() {
		var i ListTicketEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.StaffID,
			&i.StaffFirstName,
			&i.StaffLastName,
			&i.Kind,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTicketAnswered = `-- name: MarkTicketAnswered :exec
UPDATE ticket SET is_answered = true, last_response_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) MarkTicketAnswered(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markTicketAnswered, id)
	return err
}

const setTicketAssignee = `-- name: SetTicketAssignee :exec
UPDATE ticket SET assigned_staff_id = $2, updated_at = now() WHERE id = $1
`

type SetTicketAssigneeParams struct {
	ID              int64
	AssignedStaffID *int64
}

func (q *Queries) SetTicketAssignee(ctx context.Context, arg SetTicketAssigneeParams) error {
	_, err := q.db.Exec(ctx, setTicketAssignee, arg.ID, arg.AssignedStaffID)
	return err
}

const setTicketDept = `-- name: SetTicketDept :exec
UPDATE ticket SET dept_id = $2, updated_at = now() WHERE id = $1
`

type SetTicketDeptParams struct {
	ID     int64
	DeptID int64
}

func (q *Queries) SetTicketDept(ctx context.Context, arg SetTicketDeptParams) error {
	_, err := q.db.Exec(ctx, setTicketDept, arg.ID, arg.DeptID)
	return err
}

const setTicketStatus = `-- name: SetTicketStatus :exec
UPDATE ticket
SET status_id = $1,
    closed_at = CASE WHEN $2::boolean THEN clock_timestamp() WHEN $3::boolean THEN NULL ELSE closed_at END,
    updated_at = now()
WHERE id = $4
`

type SetTicketStatusParams struct {
	StatusID int64
	Close    bool
	Reopen   bool
	ID       int64
}

// closed_at is set from the database clock (clock_timestamp(), not now(),
// for the same reason as CreateTicket) rather than a Go-side time.Now(), so
// the app server's clock can never disagree with what's stored.
func (q *Queries) SetTicketStatus(ctx context.Context, arg SetTicketStatusParams) error {
	_, err := q.db.Exec(ctx, setTicketStatus,
		arg.StatusID,
		arg.Close,
		arg.Reopen,
		arg.ID,
	)
	return err
}
