// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket.sql

package db

import (
	"context"
	"time"
)

const countTickets = `-- name: CountTickets :one
SELECT count(*)::bigint
FROM ticket t
JOIN ticket_status s ON s.id = t.status_id
WHERE ($1::boolean OR t.dept_id = ANY($2::bigint[]))
  AND ($3::bigint IS NULL OR t.status_id = $3)
  AND ($4::text IS NULL OR s.state::text = $4)
  AND ($5::bigint IS NULL OR t.dept_id = $5)
  AND ($6::bigint IS NULL OR t.assigned_staff_id = $6)
  AND (NOT $7::boolean OR t.assigned_staff_id IS NULL)
  AND ($8::text = '' OR to_tsvector('english', t.subject) @@ plainto_tsquery('english', $8))
`

type CountTicketsParams struct {
	AllDepts        bool
	DeptIds         []int64
	StatusID        *int64
	State           *string
	FilterDeptID    *int64
	AssignedStaffID *int64
	Unassigned      bool
	Q               string
}

func (q *Queries) CountTickets(ctx context.Context, arg CountTicketsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTickets,
		arg.AllDepts,
		arg.DeptIds,
		arg.StatusID,
		arg.State,
		arg.FilterDeptID,
		arg.AssignedStaffID,
		arg.Unassigned,
		arg.Q,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createThreadEntry = `-- name: CreateThreadEntry :one
INSERT INTO thread_entry (ticket_id, type, staff_id, poster, title, body, format, parent_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, ticket_id, type, staff_id, poster, title, body, format, parent_id, created_at, updated_at
`

type CreateThreadEntryParams struct {
	TicketID int64
	Type     ThreadEntryType
	StaffID  *int64
	Poster   string
	Title    *string
	Body     string
	Format   BodyFormat
	ParentID *int64
}

func (q *Queries) CreateThreadEntry(ctx context.Context, arg CreateThreadEntryParams) (ThreadEntry, error) {
	row := q.db.QueryRow(ctx, createThreadEntry,
		arg.TicketID,
		arg.Type,
		arg.StaffID,
		arg.Poster,
		arg.Title,
		arg.Body,
		arg.Format,
		arg.ParentID,
	)
	var i ThreadEntry
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.Type,
		&i.StaffID,
		&i.Poster,
		&i.Title,
		&i.Body,
		&i.Format,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO ticket (number, subject, status_id, dept_id, topic_id, priority_id,
                    requester_name, requester_email, source, due_at, extra,
                    last_message_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, clock_timestamp(), clock_timestamp(), clock_timestamp())
RETURNING id
`

type CreateTicketParams struct {
	Number         string
	Subject        string
	StatusID       int64
	DeptID         int64
	TopicID        *int64
	PriorityID     int64
	RequesterName  string
	RequesterEmail string
	Source         TicketSource
	DueAt          *time.Time
	Extra          []byte
}

// clock_timestamp() (not now()) so tickets created in quick succession inside
// one wrapping transaction (as in tests) still get distinct, real-time-ordered
// created_at/last_message_at values; now() is frozen for the whole transaction.
func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (int64, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.Number,
		arg.Subject,
		arg.StatusID,
		arg.DeptID,
		arg.TopicID,
		arg.PriorityID,
		arg.RequesterName,
		arg.RequesterEmail,
		arg.Source,
		arg.DueAt,
		arg.Extra,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createTicketEvent = `-- name: CreateTicketEvent :exec
INSERT INTO ticket_event (ticket_id, staff_id, kind, data) VALUES ($1, $2, $3, $4)
`

type CreateTicketEventParams struct {
	TicketID int64
	StaffID  *int64
	Kind     TicketEventKind
	Data     []byte
}

func (q *Queries) CreateTicketEvent(ctx context.Context, arg CreateTicketEventParams) error {
	_, err := q.db.Exec(ctx, createTicketEvent,
		arg.TicketID,
		arg.StaffID,
		arg.Kind,
		arg.Data,
	)
	return err
}

const getTicket = `-- name: GetTicket :one
SELECT t.id, t.number, t.subject,
       t.status_id, s.name AS status_name, s.state AS status_state,
       t.dept_id, d.name AS dept_name,
       t.topic_id, ht.name AS topic_name,
       t.priority_id, p.name AS priority_name,
       t.assigned_staff_id, st.first_name AS assignee_first_name, st.last_name AS assignee_last_name,
       t.requester_name, t.requester_email, t.source, t.is_answered,
       t.due_at, t.closed_at, t.last_message_at, t.last_response_at, t.extra,
       t.created_at, t.updated_at
FROM ticket t
JOIN ticket_status s ON s.id = t.status_id
JOIN department d ON d.id = t.dept_id
JOIN ticket_priority p ON p.id = t.priority_id
LEFT JOIN help_topic ht ON ht.id = t.topic_id
LEFT JOIN staff st ON st.id = t.assigned_staff_id
WHERE t.id = $1
`

type GetTicketRow struct {
	ID                int64
	Number            string
	Subject           string
	StatusID          int64
	StatusName        string
	StatusState       TicketState
	DeptID            int64
	DeptName          string
	TopicID           *int64
	TopicName         *string
	PriorityID        int64
	PriorityName      string
	AssignedStaffID   *int64
	AssigneeFirstName *string
	AssigneeLastName  *string
	RequesterName     string
	RequesterEmail    string
	Source            TicketSource
	IsAnswered        bool
	DueAt             *time.Time
	ClosedAt          *time.Time
	LastMessageAt     time.Time
	LastResponseAt    *time.Time
	Extra             []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) GetTicket(ctx context.Context, id int64) (GetTicketRow, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i GetTicketRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Subject,
		&i.StatusID,
		&i.StatusName,
		&i.StatusState,
		&i.DeptID,
		&i.DeptName,
		&i.TopicID,
		&i.TopicName,
		&i.PriorityID,
		&i.PriorityName,
		&i.AssignedStaffID,
		&i.AssigneeFirstName,
		&i.AssigneeLastName,
		&i.RequesterName,
		&i.RequesterEmail,
		&i.Source,
		&i.IsAnswered,
		&i.DueAt,
		&i.ClosedAt,
		&i.LastMessageAt,
		&i.LastResponseAt,
		&i.Extra,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketByNumber = `-- name: GetTicketByNumber :one
SELECT id FROM ticket WHERE number = $1
`

func (q *Queries) GetTicketByNumber(ctx context.Context, number string) (int64, error) {
	row := q.db.QueryRow(ctx, getTicketByNumber, number)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listTickets = `-- name: ListTickets :many
SELECT t.id, t.number, t.subject,
       t.status_id, s.name AS status_name, s.state AS status_state,
       t.dept_id, d.name AS dept_name,
       t.topic_id, ht.name AS topic_name,
       t.priority_id, p.name AS priority_name,
       t.assigned_staff_id, st.first_name AS assignee_first_name, st.last_name AS assignee_last_name,
       t.requester_name, t.requester_email, t.source, t.is_answered,
       t.due_at, t.closed_at, t.last_message_at, t.last_response_at, t.extra,
       t.created_at, t.updated_at
FROM ticket t
JOIN ticket_status s ON s.id = t.status_id
JOIN department d ON d.id = t.dept_id
JOIN ticket_priority p ON p.id = t.priority_id
LEFT JOIN help_topic ht ON ht.id = t.topic_id
LEFT JOIN staff st ON st.id = t.assigned_staff_id
WHERE ($1::boolean OR t.dept_id = ANY($2::bigint[]))
  AND ($3::bigint IS NULL OR t.status_id = $3)
  AND ($4::text IS NULL OR s.state::text = $4)
  AND ($5::bigint IS NULL OR t.dept_id = $5)
  AND ($6::bigint IS NULL OR t.assigned_staff_id = $6)
  AND (NOT $7::boolean OR t.assigned_staff_id IS NULL)
  AND ($8::text = '' OR to_tsvector('english', t.subject) @@ plainto_tsquery('english', $8))
ORDER BY
  CASE WHEN $9::text = 'created_at' THEN t.created_at END ASC,
  CASE WHEN $9::text = '-created_at' THEN t.created_at END DESC,
  CASE WHEN $9::text = 'last_message_at' THEN t.last_message_at END ASC,
  CASE WHEN $9::text = '-last_message_at' THEN t.last_message_at END DESC,
  CASE WHEN $9::text = 'priority' THEN p.urgency END ASC,
  CASE WHEN $9::text = '-priority' THEN p.urgency END DESC,
  t.id DESC
LIMIT $11::int OFFSET $10::int
`

type ListTicketsParams struct {
	AllDepts        bool
	DeptIds         []int64
	StatusID        *int64
	State           *string
	FilterDeptID    *int64
	AssignedStaffID *int64
	Unassigned      bool
	Q               string
	Sort            string
	PageOffset      int32
	PageSize        int32
}

type ListTicketsRow struct {
	ID                int64
	Number            string
	Subject           string
	StatusID          int64
	StatusName        string
	StatusState       TicketState
	DeptID            int64
	DeptName          string
	TopicID           *int64
	TopicName         *string
	PriorityID        int64
	PriorityName      string
	AssignedStaffID   *int64
	AssigneeFirstName *string
	AssigneeLastName  *string
	RequesterName     string
	RequesterEmail    string
	Source            TicketSource
	IsAnswered        bool
	DueAt             *time.Time
	ClosedAt          *time.Time
	LastMessageAt     time.Time
	LastResponseAt    *time.Time
	Extra             []byte
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]ListTicketsRow, error) {
	rows, err := q.db.Query(ctx, listTickets,
		arg.AllDepts,
		arg.DeptIds,
		arg.StatusID,
		arg.State,
		arg.FilterDeptID,
		arg.AssignedStaffID,
		arg.Unassigned,
		arg.Q,
		arg.Sort,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTicketsRow{}
	for rows.Next() {
		var i ListTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Subject,
			&i.StatusID,
			&i.StatusName,
			&i.StatusState,
			&i.DeptID,
			&i.DeptName,
			&i.TopicID,
			&i.TopicName,
			&i.PriorityID,
			&i.PriorityName,
			&i.AssignedStaffID,
			&i.AssigneeFirstName,
			&i.AssigneeLastName,
			&i.RequesterName,
			&i.RequesterEmail,
			&i.Source,
			&i.IsAnswered,
			&i.DueAt,
			&i.ClosedAt,
			&i.LastMessageAt,
			&i.LastResponseAt,
			&i.Extra,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTicket = `-- name: LockTicket :exec
SELECT id FROM ticket WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockTicket(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, lockTicket, id)
	return err
}

const nextTicketNumber = `-- name: NextTicketNumber :one
SELECT nextval('ticket_number_seq')::bigint
`

func (q *Queries) NextTicketNumber(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextTicketNumber)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateTicket = `-- name: UpdateTicket :exec
UPDATE ticket
SET subject = COALESCE($1, subject),
    priority_id = COALESCE($2, priority_id),
    topic_id = CASE WHEN $3::boolean THEN NULL ELSE COALESCE($4, topic_id) END,
    due_at = CASE WHEN $5::boolean THEN NULL ELSE COALESCE($6, due_at) END,
    extra = COALESCE($7, extra),
    requester_name = COALESCE($8, requester_name),
    requester_email = COALESCE($9, requester_email),
    updated_at = now()
WHERE id = $10
`

type UpdateTicketParams struct {
	Subject        *string
	PriorityID     *int64
	ClearTopic     bool
	TopicID        *int64
	ClearDueAt     bool
	DueAt          *time.Time
	Extra          []byte
	RequesterName  *string
	RequesterEmail *string
	ID             int64
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) error {
	_, err := q.db.Exec(ctx, updateTicket,
		arg.Subject,
		arg.PriorityID,
		arg.ClearTopic,
		arg.TopicID,
		arg.ClearDueAt,
		arg.DueAt,
		arg.Extra,
		arg.RequesterName,
		arg.RequesterEmail,
		arg.ID,
	)
	return err
}
