// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topic.sql

package db

import (
	"context"
)

const countTopicReferences = `-- name: CountTopicReferences :one
SELECT count(*)::bigint FROM ticket WHERE topic_id = $1
`

func (q *Queries) CountTopicReferences(ctx context.Context, topicID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countTopicReferences, topicID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTopic = `-- name: CreateTopic :one
INSERT INTO help_topic (name, dept_id, priority_id, is_active, sort_order)
VALUES ($1, $2, $3, $4, $5) RETURNING id, name, dept_id, priority_id, is_active, sort_order, created_at, updated_at
`

type CreateTopicParams struct {
	Name       string
	DeptID     *int64
	PriorityID *int64
	IsActive   bool
	SortOrder  int32
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (HelpTopic, error) {
	row := q.db.QueryRow(ctx, createTopic,
		arg.Name,
		arg.DeptID,
		arg.PriorityID,
		arg.IsActive,
		arg.SortOrder,
	)
	var i HelpTopic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeptID,
		&i.PriorityID,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTopic = `-- name: DeleteTopic :execrows
DELETE FROM help_topic WHERE id = $1
`

func (q *Queries) DeleteTopic(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTopic, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTopic = `-- name: GetTopic :one
SELECT id, name, dept_id, priority_id, is_active, sort_order, created_at, updated_at FROM help_topic WHERE id = $1
`

func (q *Queries) GetTopic(ctx context.Context, id int64) (HelpTopic, error) {
	row := q.db.QueryRow(ctx, getTopic, id)
	var i HelpTopic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeptID,
		&i.PriorityID,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTopics = `-- name: ListTopics :many
SELECT id, name, dept_id, priority_id, is_active, sort_order, created_at, updated_at FROM help_topic ORDER BY sort_order, name
`

func (q *Queries) ListTopics(ctx context.Context) ([]HelpTopic, error) {
	rows, err := q.db.Query(ctx, listTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HelpTopic{}
	for rows.Next() {
		var i HelpTopic
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DeptID,
			&i.PriorityID,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTopic = `-- name: UpdateTopic :one
UPDATE help_topic
SET name = COALESCE($1, name),
    dept_id = CASE WHEN $2::boolean THEN NULL ELSE COALESCE($3, dept_id) END,
    priority_id = CASE WHEN $4::boolean THEN NULL ELSE COALESCE($5, priority_id) END,
    is_active = COALESCE($6, is_active),
    sort_order = COALESCE($7, sort_order),
    updated_at = now()
WHERE id = $8
RETURNING id, name, dept_id, priority_id, is_active, sort_order, created_at, updated_at
`

type UpdateTopicParams struct {
	Name          *string
	ClearDept     bool
	DeptID        *int64
	ClearPriority bool
	PriorityID    *int64
	IsActive      *bool
	SortOrder     *int32
	ID            int64
}

func (q *Queries) UpdateTopic(ctx context.Context, arg UpdateTopicParams) (HelpTopic, error) {
	row := q.db.QueryRow(ctx, updateTopic,
		arg.Name,
		arg.ClearDept,
		arg.DeptID,
		arg.ClearPriority,
		arg.PriorityID,
		arg.IsActive,
		arg.SortOrder,
		arg.ID,
	)
	var i HelpTopic
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DeptID,
		&i.PriorityID,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
